version: "3.7"
services:
  # webserver:
  #     image: nginx:latest
  #     container_name: webserver
  #     volumes:
  #       - /home/jarvislu/linebot/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  #       - /home/jarvislu/linebot/nginx/ssl/:/etc/nginx/ssl/
  #     ports:
  #       - 443:443
  #     depends_on:
  #       - web
  #     networks:
  #       customnetwork:
  #         ipv4_address: 172.10.0.8
  web:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: pyflask_env
      volumes:
        - /home/jarvislu/linebot/:/home/linebot/
      networks:
        customnetwork:
          ipv4_address: 172.10.0.9
      ports:
        - 80:5000
      working_dir: /home/linebot/
      command: uwsgi --ini app.ini

networks:
  customnetwork:
    ipam:
      config:
        - subnet: 172.10.0.0/16 

